# Generated by Django 5.2.1 on 2026-02-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_apiclient_remove_device_user_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('default_data', models.JSONField(blank=True, default=dict)),
                ('platform_overrides', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.apiclient')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('events', models.JSONField(default=list)),
                ('secret_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.apiclient')),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('credentials_json', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_projects', to='notification.apiclient')),
            ],
            options={
                'unique_together': {('api_client', 'project_name')},
            },
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('avg_delivery_time_ms', models.IntegerField(null=True)),
                ('api_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.apiclient')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.topic')),
            ],
            options={
                'unique_together': {('date', 'api_client', 'topic', 'platform')},
            },
        ),
    ]
