# Generated by Django 5.2.1 on 2026-02-17 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationtemplate_webhookendpoint_firebaseproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='click_action',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='collapse_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_silent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data_payload', models.JSONField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal')], default='high', max_length=10)),
                ('is_silent', models.BooleanField(default=False)),
                ('click_action', models.URLField(blank=True, default='')),
                ('template_variables', models.JSONField(blank=True, null=True)),
                ('phone_numbers', models.JSONField(default=list)),
                ('topic', models.CharField(blank=True, default='', max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('repeat_interval', models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('max_occurrences', models.IntegerField(blank=True, null=True)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.apiclient')),
                ('firebase_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.firebaseproject')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationtemplate')),
            ],
        ),
    ]
