# Generated by Django 5.2.1 on 2026-06-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_apiclient_expiry_scopes_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
